# Uncomment the next line to define a global platform for your project

source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'
use_frameworks!

target 'example' do

  pod 'butterfly',:path =>'../butterfly'
  pod 'RenderImage',:path =>'../RenderImage'
  pod 'Database',:path =>'../Database'
  pod 'SPUAlert',:path =>'../SPUAlert'
  pod 'Bit',:path =>'../Bit'
  pod 'Dessert',:path =>'../Dessert'
end

target 'testBIT' do

  pod 'butterfly',:path =>'../butterfly'
  pod 'RenderImage',:path =>'../RenderImage'
  pod 'Database',:path =>'../Database'
  pod 'SPUAlert',:path =>'../SPUAlert'
  pod 'Bit',:path =>'../Bit'
  pod 'Dessert',:path =>'../Dessert'
end
